### ISSUE TITLE
关于 kubernets 相关 image 问题

### ISSUE THREAD

**Issue by mritd** [ChasonTang/docker-library#1]
看了博主关于 k8s 1.4 的文章，有点疑惑想问下:

k8s 1.4 的 kubeadm 会下载一些 gcr.io 的 image，这些 image 我看博主都是自己写了一个 Dockerfile，然后 From 的；但是如何得知 这些镜像的版本？ 比如现在 gcr.io/google_containers/kubedns-amd64 是 1.7，那么将来会有 1.8，这个版本更新从哪得到？

我有台国外服务器，想在跑个脚本啥的定期来更新这些镜像，但不知道怎么检测这些镜像是否有更新

**Comment by ChasonTang** [comment]
目前 apiserver、controller-manager 等倒是可以知道，直接就是那个版本作为 tag，但是像 discovery、dns 等就没有办法了，只能通过查日志查看报错的 image

**Comment by mritd** [comment]
......我 google 了半天，感觉这个事有点蛋疼.......先用着吧  哈哈
